name: flutter_map_gl
description: "A Flutter package that allows you to use maps in mobile applications (iOS and Android)."
version: 1.0.0
homepage: https://github.com/muhammedfurkansahin/flutter_map_gl
repository: https://github.com/muhammedfurkansahin/flutter_map_gl
issue_tracker: https://github.com/muhammedfurkansahin/flutter_map_gl/issues
documentation: https://github.com/muhammedfurkansahin/flutter_map_gl/blob/main/README.md

# Indicates that it only supports iOS and Android platforms
platforms:
  android: 
  ios:

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.11.0 # For creating WebView-based maps
  webview_flutter_android: ^4.4.2
  webview_flutter_wkwebview: ^3.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
